/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
    FIREBASE_APPCHECK_DEBUG_TOKEN: process.env.FIREBASE_APPCHECK_DEBUG_TOKEN,
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,

    RECAPTCHA_SITE_KEY: process.env.RECAPTCHA_SITE_KEY,

    IS_TESTING_FROM_CI: process.env.IS_TESTING_FROM_CI,

    JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,

    CRON_SECRET: process.env.CRON_SECRET,
    CRON_SECRET_TEST: process.env.CRON_SECRET_TEST,

    MESSAGE_BEARER_KEY: process.env.MESSAGE_BEARER_KEY,
    TEST_MESSAGE_BEARER_KEY: process.env.TEST_MESSAGE_BEARER_KEY,

    PRODUCTION_REFERER: process.env.PRODUCTION_REFERER
  }
}

module.exports = nextConfig
