/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
    FIREBASE_APP_CHECK_DEBUG_TOKEN: process.env.FIREBASE_APP_CHECK_DEBUG_TOKEN,

    RECAPTCHA_SITE_KEY: process.env.RECAPTCHA_SITE_KEY,

    IS_TESTING_FROM_CI: process.env.IS_TESTING_FROM_CI,

    JWT_SECRET_KEY: process.env.JWT_SECRET_KEY
  }
}

module.exports = nextConfig
